apiVersion: v1
kind: Service
metadata:
  name: blogger-app-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 31000
    port: 8091
    targetPort: 8000 
  selector:
    app: blogger_app
