apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogger-api-deployment
  labels:
    app: blogger_api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blogger_api
  template:
    metadata:
      labels:
        app: blogger_api
    spec:
      containers:
      - name: apiappcontainer
        image: 35783594/blogger_api:latest
        ports:
        - containerPort: 3000
        env:
          - name: POSTGRES_HOST
            value: "postgres-service"
          - name: POSTGRES_DB
            value: "blog_db"
          - name: POSTGRES_USER
            value: "blogger"
          - name: POSTGRES_PASSWORD
            value: "Self.blogdb"