apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: myNewUserRoleBinding
 namespace: default
subjects:
- kind: User
  name: newuser
roleRef:
 kind: Role
 name: mynewuser
 apiGroup: rbac.authorization.k8s.io
