apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: myNewDevRoleBinding
 namespace: default
subjects:
- kind: User
  name: developer
roleRef:
 kind: Role
 name: mynewdeveloper
 apiGroup: rbac.authorization.k8s.io
