apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: myViewUserRoleBinding
 namespace: default
subjects:
- kind: User
  name: viewuser
roleRef:
 kind: Role
 name: myviewuser
 apiGroup: rbac.authorization.k8s.io
